django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),  # as_view() method used to call class based view
    path('people', views.PersonList.as_view(), name='PersonList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id/image/upload', views.MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('top_10_movies', views.TopMovies.as_view(), name='TopMovies'),
]

django/core/models.py
from uuid import uuid4

from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class Person(models.Model):
    first_name = models.CharField(
        max_length=140)
    last_name = models.CharField(
        max_length=140)
    born = models.DateField()
    died = models.DateField(null=True,
                            blank=True)

    objects = PersonManager()

    class Meta:
        ordering = (
            'last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
                self.last_name,
                self.first_name,
                self.born)


class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G,
         'G - General Audiences'),
        (RATED_PG,
         'PG - Parental Guidance '
         'Suggested'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(
        max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(
        blank=True)
    director = models.ForeignKey(
        to='Person',
        null=True,
        on_delete=models.SET_NULL,
        related_name='directed',
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(
            self.title, self.year)


def movie_directory_path_with_uuid(instance, filename):
    return {}/{}.format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie',
                           'person',
                           'name')


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)  
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, '👍',),
        (DOWN, '👎',),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

django/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True)
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True)
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,)

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True)
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True)

    class Meta:
        models = MovieImage
        fields = ('image', 'user', 'movie')

django/core/views.py
import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView


from core.forms import VoteForm, MovieImageForm
from core.models import Movie, Person, Vote
from core.mixins import CachePageVaryOnCookieMixin


class MovieList(CachePageVaryOnCookieMixin, ListView):
    model = Movie
    paginate_by = 10

    def get_context_data(self, **kwargs):
        ctx = super(MovieList, self).get_context_data(**kwargs)
        page = ctx['page_obj']
        paginator = ctx['paginator']
        ctx['page_is_first'] = (
            page.number == 1)
        ctx['page_is_last'] = (
            page.number == paginator.num_pages)
        return ctx


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            # checking django version
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)
        return qs


class MovieDetail(DetailView):
    queryset = (Movie.objects.all_with_related_persons_and_score())

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object, user=self.request.user)
            if vote.id:
                vote_form_url = reverse('core:UpdateVote',
                                        kwargs={
                                            'movie_id': vote.movie.id,
                                            'pk': vote.id})
            else:
                vote_form_url = reverse('core:CreateVote',
                                        kwargs={'movie_id': self.object.id})
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return movie_detail_url


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail',
                                   kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied('Cannot change another users vote')
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail',
                                   kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class PersonList(ListView):
    model = Person
    paginate_by = 10


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<p class="lead">
  {{ object.plot }}
</p>
<div>
  <ul class="movie-image list-inline">
    {% for i in object.movieimage_set.all %}
    <li class="list-inline-item">
      <img src="{{ i.image.url }}">
    </li>
    {% endfor %}
  </ul>
  <h2>Director</h2>
  <p>
    {{ object.director }}
  </p>
  <h2>Written by:</h2>
  <ul>
    {% for writer in object.writers.all %}
    <li>
      {{ writer }}
    </li>
    {% endfor %}
  </ul>
  <h2>Actors</h2>
  <ul>
    {% for role in object.role_set.all %}
    <li>
      <a href="{% url 'core:PersonDetail' pk=role.person.id %}">
        {{ role.person }}: {{ role.name}}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}


{% block sidebar %}
<div>
  This movie is rated:
  <span class="badge badge-primary">
    {{ object.get_rating_display }}
  </span>
</div>
{% if image_form %}
<div>
  <h2>Upload New Image</h2>
  <form method="post" enctype="multipart/form-data" action="{% url 'core:MovieImageUpload' movie_id=object.id %}">
    {% csrf_token %}
    {{ image_form.as_p }}
    <p>
      <button class="btn btn-primary">
        Upload
      </button>
    </p>
  </form>
</div>
{% endif %}
<div>
  <h2>
    Score: {{ object.score|default_if_none:"TBD" }}
  </h2>
</div>
<div>
  {% if vote_form %}
  <form method="POST" action="{{ vote_form_url }}">
    {% csrf_token %}
    {{ vote_form.as_p }}
    <button class="btn btn-primary">
      Vote
    </button>
  </form>
  {% else %}
  <p>Please Log in to Vote</p>
  {% endif %}
</div>
{% endblock %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
All Movies
{% endblock %}

{% block main %}
<ul>
    {% for movie in object_list %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
            {{ movie }}
        </a>
    </li>
    {% endfor %}
</ul>
{% if is_paginated %}
    <nav>
        <ul class="pagination">
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page=1"
                    class="page-link"
                >
                    First
                </a>
            </li>
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
                    class="page-link"
                >
                    {{ page_obj.previous_page_number }}
                </a>
            </li>
            {% endif %}
            <li class="page-item active">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
                    class="page-link"
                >
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
                    class="page-link"
                >
                    {{ page_obj.next_page_number }}
                </a>
            </li>
            {% endif %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page=last"
                    class="page-link"    
                >
                    Last
                </a>
            </li>
        </ul>
    </nav>
    {% endif %}
{% endblock %}

django/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.first_name }}
  {{ object.last_name }}
{% endblock %}

{% block main %}

  <h1>{{ object }}</h1>
  <h2>Actor</h2>
  <ul >
    {% for role in object.role_set.all %}
      <li >
        <a href="{% url 'core:MovieDetail' role.movie.id %}" >
          {{ role.movie }} 
        </a >: {{ role.name }}
      </li >
    {% endfor %}
  </ul >
  <h2>Writer</h2>
  <ul >
    {% for movie in object.writing_credits.all %}
      <li >
        <a href="{% url 'core:MovieDetail' movie.id %}" >
          {{ movie }}
        </a >
      </li >
    {% endfor %}
  </ul >
  <h2>Director</h2>
  <ul >
    {% for movie in object.directed.all %}
      <li >
        <a href="{% url 'core:MovieDetail' movie.id %}" >
          {{ movie }}
        </a >
      </li >
    {% endfor %}
  </ul >

{% endblock %}

django/core/templates/core/person_list.html
{% extends 'base.html' %}

{% block title %}
All People
{% endblock %}

{% block main %}
<ul>
    {% for person in object_list %}
    <li>
        <a href="{% url 'core:PersonDetail' pk=person.id %}">
            {{ person }}
        </a>
    </li>
    {% endfor %}
</ul>
{% if is_paginated %}
    <nav>
        <ul class="pagination">
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page=1"
                    class="page-link"
                >
                    First
                </a>
            </li>
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
                    class="page-link"
                >
                    {{ page_obj.previous_page_number }}
                </a>
            </li>
            {% endif %}
            <li class="page-item active">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
                    class="page-link"
                >
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
                    class="page-link"
                >
                    {{ page_obj.next_page_number }}
                </a>
            </li>
            {% endif %}
            <li class="page-item">
                <a
                    href="{% url 'core:MovieList' %}?page=last"
                    class="page-link"    
                >
                    Last
                </a>
            </li>
        </ul>
    </nav>
    {% endif %}
{% endblock %}

django/core/templates/core/top_movies.html
{% extends 'base.html' %}

{% block title %}
<title>Top 10 Movies</title>
{% endblock %}

{% block main %}
<h1>Top 10 Movies</h1>
<ol>
    {% for movies in object_list %}
    <li>
        <a href="{% url 'c
        
        ore:MovieDetail' pk=movie.id %}">
            {{ movie }}
        </a>
    </li>
    {% endfor }
</ol>
{% endblock %}