django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),  # as_view() method used to call class based view
    path('people', views.PersonList.as_view(), name='PersonList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id/image/upload', views.MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('top_10_movies', views.TopMovies.as_view(), name='TopMovies'),
]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta 
        name = "viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
    >
    <link
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
        integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
        rel="stylesheet"
        crossorigin="anonymous"
    >
    <title>
        {% block title %}MyMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class = "mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">MyMDB</div>
            <a class="nav-link" href="{% url 'core:MovieList' %}">
                Movies
            </a>
            <a class="nav-link" href="{% url 'core:PersonList' %}">
                People
            </a>
            <a class="nav-link" href="{% url 'core:TopMovies' %}">
                Top 10 Movies
            </a>
            <a class="nav-link" href="{% url 'user:register' %}">
                Register
            </a>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'user:logout' %}">
                Log Out
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'user:login' %}">
                    Log In
                </a>
            {% endif %}
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>